<?php ?>
<footer id="footer" role="contentinfo">
	<div class="layer">
        <div class="layer-area">
            <div class="stat-grids">
				<a href="#l-document"><i class="top-btn fas fa-angle-up"></i> ページトップへ</a>
			</div>
		</div>
	</div>	
	 <div class="content-bottom">
		<div class="evaluates">
			<a href="">
				<span class="txt_download">評価版ダウンロード</span>
				<span class="txt_download_list">
                        <span>・ もちろん無料</span>
                        <span>・ 期間限定で全機能が使用可能</span>
                        <span>・ 配布自由</span>
                </span>
				 <i class="fas fa-arrow-right"></i>
			</a>
			<a href="#"><span class="txt_download">お見積もり</span><i class="fas fa-arrow-right"></i></a> 

           
	
		</div><!-- review-area -->		
	</div><!-- content-bottom -->
	<div class="clear"></div>
	<div id="footer-top">
		<div class="">
			<div class="review-area">
				<div class="review-left">
					<h4>Lightning Reviewに関するお問い合わせ</h4>
					<ul class="nav-info">
						<li><a>Lightning Review 営業窓口</a></li>
						<li><a>e-mail: lrsales@dcinc.co.jp</a></li>
						<li><a>TEL:052-238-0499</a></li>
					</ul>
				</div>
				<div class="review-right">
					<div class="title-20"><a>お問い合わせ <i class="fas fa-arrow-right"></i></a></div>
				</div>
			</div>
		</div>
	</div>
	
	<div id="footer-bottom">
		<div class="wrapper-area">
			<nav class="nav_contentinfo">
						<ul class="nav_footer_top">
							<li><a href="★★★" target="_blank">トップページ</a></li>
							<li><a href="★★★">ニュース</a></li>
							<li><a href="★★★">コンセプト</a></li>
							<li><a href="★★★">特長</a></li>
							<li><a href="★★★">導入効果</a></li>
							<li><a href="★★★">ご購入について</a></li>
							<li><a href="★★★">お問い合わせ</a></li>
							<li><a href="★★★">サポート</a></li>
							<li><a href="★★★">製品紹介セミナー</a></li>
							<li><a href="★★★">ログイン</a></li>
							
						</ul>
					</nav>
		</div>
		<div id="border-line">
				<div class="wrapper-area d-block">
					<div class="border-line-left">
						<div class="border-line-title">
							<h3><img src="/common/images/denso_logo.png" /></h3>
						</div>
					</div>		
					<div class="border-line-center">
						<ul class="nav_footer_bt">
								<li class="column"><a href="★★★" target="_blank">ーポレートサイト</a></li>
								<li class="column"><a href="★★★">その他の製品・サービス</a></li>
								<li class="column"><a href="★★★">このサイトのご利用について</a></li>
								<li class="column"><a href="★★★">個人情報保護</a></li>
						</ul>	
					</div>
					<div class="border-line-right">
						<img src="/assets/images/logo-timetracker.png" />
						 <div class="media-social">
						 	  <a class="btn-outline-light btn-social mx-1" href="#">
								<i class="fab fa-fw fa-facebook-f"></i>
							  </a>
							  <a class="btn-outline-light btn-social mx-1" href="#">
								<i class="fab fa-fw fa-twitter"></i>
							  </a>
						 </div>
						 

					</div>
					
				</div>
		</div>
	
		
		<div class="footer-copyright">
			<div class="wrapper-area">
				
					<div class="float-sm-right p-2">
						<p class="txt_copyright"><small>Copyright &copy; DENSO CREATE INC, All rights reserved.</small></p>
					</div>
				
				
				
			</div>
		</div>
		
	</div>
	
</footer>
<!--p class="nav_backtotop"><a href="#document">このページの先頭へ戻る</a></p-->
